#!/bin/bash
set -e

os_type=$(uname -s)

#
# Install prerequisites
#

if [[ "$UID" == 0 ]]; then
  SUDO=""
else
  SUDO=`which sudo 2>/dev/null`
fi

case $os_type in
  Darwin)
    brew install rcm zplug
    ;;
  Linux)
    $SUDO apt-get update -y
    $SUDO apt-get install -y git wget apt-transport-https
    wget -qO - https://apt.thoughtbot.com/thoughtbot.gpg.key | \
      $SUDO apt-key add -
    echo "deb https://apt.thoughtbot.com/debian/ stable main" | \
      $SUDO tee /etc/apt/sources.list.d/thoughtbot.list
    $SUDO apt-get update -y
    $SUDO apt-get install -y rcm

    curl -sL --proto-redir -all,https https://raw.githubusercontent.com/zplug/installer/master/installer.zsh | zsh
    ;;
  *)
    echo "Fatal: Unsupported OS"
    exit 1
    ;;
esac

#
# Purge abandoned setups
#

rm -rf ~/.oh-my-zsh ~/.freistil-dotfiles

#
# Clone dotfiles repo
#

if [[ -d ~/.dotfiles ]]; then
  cd ~/.dotfiles
  git pull
else
  git clone https://github.com/geewiz/dotfiles.git ~/.dotfiles
fi

#
# Run setup
#

rcup -f -t $os_type -d ~/.dotfiles
reset
