prompt_order = [
  "username",
  "hostname",
  "ruby",
  "package",
  "nodejs",
  "rust",
  "python",
  "golang",
  "java",
  "nix_shell",
  "directory",
  "git_branch",
  "git_state",
  "git_status",
  "aws",
  "env_var",
  "cmd_duration",
  "line_break",
  "jobs",
  "battery",
  "time",
  "character",
]

[hostname]
disabled = false
ssh_only = true
prefix = "⟪"
suffix = "⟫"

[username]
disabled = false
show_always = true
ssh_only = false

[aws]
disabled = true

